# Generated by Django 4.2.27 on 2026-01-13 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time of slot')),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False, help_text='Is this slot is booked')),
                ('booked_at', models.DateTimeField(blank=True, help_text='When it was booked', null=True)),
                ('public_link', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, help_text='Who booked this slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Owner of slots , who take calling ', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
