# Generated by Django 4.2.27 on 2026-01-15 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='public_link',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Guest name for booking without registration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_link', models.CharField(max_length=100, unique=True)),
                ('owner_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to='bookings.bookingsession'),
        ),
    ]
