# Generated by Django 4.2.27 on 2026-01-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_remove_timeslot_public_link_timeslot_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
